version: '3.8'
name: educationdotnew
networks:
  net:
    driver: bridge
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
    networks:
      - net